export const SliderData = [
  { 
    image: '/designs_rat.png',
    name: 'Rat',
    traits: 'Acute, Cautious, Calm',
    bff: 'Ox',
    nemesis: 'Horse',
    years: '1972, 1984, 1996, 2008',
    element: '',
  },
  { 
    image: '/designs_ox.png',
    name: 'Ox', 
    traits: 'Persistent, Cautious, Patient',
    bff: 'Rat',
    nemesis: 'Goat',
    years: '1973, 1985, 1997, 2009',
    element: '',
  },
  { 
    image: '/designs_tiger.png',
    name: 'Tiger',
    traits: 'Powerful, Tough, Dynamic, Mighty',
    bff: 'Pig',
    nemesis: 'Monkey',
    years: '1974, 1986, 1998, 2010',
    element: '',
  },
  { 
    image: '/designs_rabbit.png',
    name: 'Rabbit',
    traits: 'Gentle, Generous, Timid',
    bff: 'Dog',
    nemesis: 'Rooster',
    years: '1975, 1987, 1999, 2011',
    element: '',
  },
  { 
    image: '/designs_dragon.png',
    name: 'Dragon',
    traits: 'Mysterious, Imaginative, Ambitious',
    bff: 'Rooster',
    nemesis: 'Dog',
    years: '1976, 1988, 2000, 2012',
    element: '',
  },
  { 
    image: '/designs_snake.png',
    name: 'Snake',
    traits: 'Wise, Humorous, Brilliant',
    bff: 'Monkey',
    nemesis: 'Pig',
    years: '1977, 1989, 2001, 2013',
    element: '',
  },
  { 
    image: '/designs_horse.png',
    name: 'Horse',
    traits: 'Energetic, Passionate',
    bff: 'Goat',
    nemesis: 'Rat',
    years: '1978, 1990, 2002, 2014',
    element: '',
  },
  { 
    image: '/designs_goat.png',
    name: 'Goat',
    traits: 'Meek, Loyal, free-spiritied',
    bff: 'Horse',
    nemesis: 'Ox',
    years: '1979, 1991, 2003, 2015',
    element: '',
  },
  { 
    image: '/designs_monkey.png',
    name: 'Monkey',
    traits: 'Cautious, Clever, Energetic',
    bff: 'Snake',
    nemesis: 'Tiger',
    years: '1980, 1992, 2004, 2016',
    element: '',
  },
  { 
    image: '/designs_rooster.png',
    name: 'Rooster',
    traits: 'Ambitious, Meticulous, Independent',
    bff: 'Dragon',
    nemesis: 'Rabbit',
    years: '1981, 1993, 2005, 2017',
    element: '',
  },
  { 
    image: '/designs_dog.png',
    name: 'Dog',
    traits: 'Loyal, Flexible, Gentle',
    bff: 'Rabbit',
    nemesis: 'Dragon',
    years: '1982, 1994, 2006, 2018',
    element: '',
  },
  { 
    image: '/designs_pig.png',
    name: 'Pig',
    traits: 'Optimistic, Gluttonous, Sleepy',
    bff: 'Tiger',
    nemesis: 'Snake',
    years: '1983, 1995, 2017, 2019',
    element: '',
  }    
]
