export const ProfileData = [
  { 
    id: 'rat',
    archetype: '',
    desc: '',
    celeb1: {name: 'a', img: ''},
    celeb2: {name: 'b', img: ''},
    celeb3: {name: 'c', img: ''},
    image: '/designs_rat.png',
    name: 'Rat',
    traits: 'Acute, Cautious, Calm',
    bff: {name: 'Ox', img:''},
    nemesis: {name: 'Horse', img:''},
    element: '',
  },
  { 
    id: 'ox',
    archetype: '',
    desc: '',
    celeb1: {name: 'a', img: ''},
    celeb2: {name: 'b', img: ''},
    celeb3: {name: 'c', img: ''},
    image: '/designs_ox.png',
    name: 'Ox', 
    traits: 'Persistent, Cautious, Patient',
    bff: {name: 'Rat', img:''},
    nemesis: {name: 'Goat', img:''},
    years: '',
    element: '',
  },
  { 
    id: 'tiger',
    archetype: '',
    desc: '',
    celeb1: {name: 'a', img: ''},
    celeb2: {name: 'b', img: ''},
    celeb3: {name: 'c', img: ''},
    image: '/designs_tiger.png',
    name: 'Tiger',
    traits: 'Powerful, Tough, Dynamic, Mighty',
    bff: {name: 'Pig', img:''},
    nemesis: {name: 'Monkey', img:''},
    years: '',
    element: '',
  },
  { 
    id: 'rabbit',
    archetype: '',
    desc: '',
    celeb1: {name: 'a', img: ''},
    celeb2: {name: 'b', img: ''},
    celeb3: {name: 'c', img: ''},
    image: '/designs_rabbit.png',
    name: 'Rabbit',
    traits: 'Gentle, Generous, Timid',
    bff: {name: 'Dog', img:''},
    nemesis: {name: 'Rooster', img:''},
    bff: 'Dog',
    nemesis: 'Rooster',
    years: '',
    element: '',
  },
  { 
    id: 'dragon',
    archetype: '',
    desc: '',
    celeb1: {name: 'a', img: ''},
    celeb2: {name: 'b', img: ''},
    celeb3: {name: 'c', img: ''},
    image: '/designs_dragon.png',
    name: 'Dragon',
    traits: 'Mysterious, Imaginative, Ambitious',
    bff: {name: 'Rooster', img:''},
    nemesis: {name: 'Dog', img:''},
    years: '',
    element: '',
  },
  { 
    id: 'snake',
    archetype: '',
    desc: '',
    celeb1: {name: 'a', img: ''},
    celeb2: {name: 'b', img: ''},
    celeb3: {name: 'c', img: ''},
    image: '/designs_snake.png',
    name: 'Snake',
    traits: 'Wise, Humorous, Brilliant',
    bff: {name: 'Monkey', img:''},
    nemesis: {name: 'Pig', img:''},
    years: '',
    element: '',
  },
  { 
    id: 'horse',
    archetype: '',
    desc: '',
    celeb1: {name: 'a', img: ''},
    celeb2: {name: 'b', img: ''},
    celeb3: {name: 'c', img: ''},
    image: '/designs_horse.png',
    name: 'Horse',
    traits: 'Energetic, Passionate',
    bff: {name: 'Goat', img:''},
    nemesis: {name: 'Rat', img:''},
    years: '',
    element: '',
  },
  { 
    id: 'goat',
    archetype: '',
    desc: '',
    celeb1: {name: 'a', img: ''},
    celeb2: {name: 'b', img: ''},
    celeb3: {name: 'c', img: ''},
    image: '/designs_goat.png',
    name: 'Goat',
    traits: 'Meek, Loyal',
    bff: {name: 'Horse', img:''},
    nemesis: {name: 'Ox', img:''},
    years: '',
    element: '',
  },
  { 
    id: 'monkey',
    archetype: '',
    desc: '',
    celeb1: {name: 'a', img: ''},
    celeb2: {name: 'b', img: ''},
    celeb3: {name: 'c', img: ''},
    image: '/designs_monkey.png',
    name: 'Monkey',
    traits: 'Cautious, Clever, Energetic',
    bff: {name: 'Snake', img:''},
    nemesis: {name: 'Tiger', img:''},
    years: '',
    element: '',
  },
  { 
    id: 'rooster',
    archetype: '',
    desc: '',
    celeb1: {name: 'a', img: ''},
    celeb2: {name: 'b', img: ''},
    celeb3: {name: 'c', img: ''},
    image: '/designs_rooster.png',
    name: 'Rooster',
    traits: 'Ambitious, Meticulous, Independent',
    bff: {name: 'Dragon', img:''},
    nemesis: {name: 'Rabbit', img:''},
    years: '',
    element: '',
  },
  { 
    id: 'dog',
    archetype: '',
    desc: '',
    celeb1: {name: 'a', img: ''},
    celeb2: {name: 'b', img: ''},
    celeb3: {name: 'c', img: ''},
    image: '/designs_dog.png',
    name: 'Dog',
    traits: 'Loyal, Flexible, Gentle',
    bff: {name: 'Rabbit', img:''},
    nemesis: {name: 'Dragon', img:''},
    years: '',
    element: '',
  },
  { 
    id: 'pig',
    archetype: '',
    desc: '',
    celeb1: {name: 'a', img: ''},
    celeb2: {name: 'b', img: ''},
    celeb3: {name: 'c', img: ''},
    image: '/designs_pig.png',
    name: 'Pig',
    traits: 'Optimistic, Gluttonous, Sleepy',
    bff: {name: 'Tiger', img:''},
    nemesis: {name: 'Snake', img:''},
    years: '',
    element: '',
  }    
]
