export const ProfileData = [
  { 
    id: 'rat',
    archetype: 'The Intelligencer',
    desc: 'Curious, clever, resourceful, and decisive, Rats are famously sharp and funny. They maneuver their way out of any tight spot with ease.',
    celeb1: {name: 'Normani', img: ''},
    celeb2: {name: 'Katy Perry', img: ''},
    celeb3: {name: 'Scarlett Johansson', img: ''},
    image: '/designs_rat.png',
    name: 'Rat',
    traits: 'Acute, Cautious, Calm',
    bff: {name: 'Ox', img:''},
    nemesis: {name: 'Horse', img:''},
    element: '',
  },
  { 
    id: 'ox',
    archetype: 'The Champion',
    desc: 'Oxes are cool and collected team players with strong principles who uphold justice and equality over personal profit and never, ever give up the fight.',
    celeb1: {name: 'Camilla Cabello', img: ''},
    celeb2: {name: 'Jungkook of BTS', img: ''},
    celeb3: {name: 'Sweet Qismina', img: ''},
    image: '/designs_ox.png',
    name: 'Ox', 
    traits: 'Persistent, Cautious, Patient',
    bff: {name: 'Rat', img:''},
    nemesis: {name: 'Goat', img:''},
    years: '',
    element: '',
  },
  { 
    id: 'tiger',
    archetype: 'The Engineer',
    desc: 'Proud and yet oddly naïve, vibrant and adventurous yet prone to tantrums, ambitious and unyielding yet friendly and warm, Tigers are full of contradictions.',
    celeb1: {name: 'a', img: ''},
    celeb2: {name: 'b', img: ''},
    celeb3: {name: 'c', img: ''},
    image: '/designs_tiger.png',
    name: 'Tiger',
    traits: 'Powerful, Tough, Dynamic, Mighty',
    bff: {name: 'Pig', img:''},
    nemesis: {name: 'Monkey', img:''},
    years: '',
    element: '',
  },
  { 
    id: 'rabbit',
    archetype: 'The Visionary',
    desc: "Bright-eyed and bushy-tailed, compassionate and sincere, Rabbits are the heart and soul of every group that they're in.",
    celeb1: {name: 'Queen Elizabeth', img: ''},
    celeb2: {name: 'Usain Bolt', img: ''},
    celeb3: {name: 'Leonardo DiCaprio', img: ''},
    image: '/designs_rabbit.png',
    name: 'Rabbit',
    traits: 'Gentle, Generous, Timid',
    bff: {name: 'Dog', img:''},
    nemesis: {name: 'Rooster', img:''},
    bff: 'Dog',
    nemesis: 'Rooster',
    years: '',
    element: '',
  },
  { 
    id: 'dragon',
    archetype: 'The Strategist',
    desc: 'Dragons are charismatic, fearless go-getters. They are natural leaders whose ambitions are only matched by the strength of their ideals.',
    celeb1: {name: 'Adele', img: ''},
    celeb2: {name: 'Jeff Bezos', img: ''},
    celeb3: {name: 'Bruce Lee', img: ''},
    image: '/designs_dragon.png',
    name: 'Dragon',
    traits: 'Mysterious, Imaginative, Ambitious',
    bff: {name: 'Rooster', img:''},
    nemesis: {name: 'Dog', img:''},
    years: '',
    element: '',
  },
  { 
    id: 'snake',
    archetype: 'The Sophisticate',
    desc: 'Passionate and fearless, charming and sly, Snakes never meet a challenge they won’t take on or a sticky situation they won’t turn in their favor.',
    celeb1: {name: 'Lucy Hale', img: ''},
    celeb2: {name: 'Logan Browning', img: ''},
    celeb3: {name: 'Chris Brown', img: ''},
    image: '/designs_snake.png',
    name: 'Snake',
    traits: 'Wise, Humorous, Brilliant',
    bff: {name: 'Monkey', img:''},
    nemesis: {name: 'Pig', img:''},
    years: '',
    element: '',
  },
  { 
    id: 'horse',
    archetype: 'The Trailblazer',
    desc: 'Assertive, expressive, and mischievous, these intrepid world travelers have hearts of gold, tongues of silver, and style in spades.',
    celeb1: {name: 'Liam Hemsworth', img: ''},
    celeb2: {name: 'Kristen Stewartb', img: ''},
    celeb3: {name: 'Dev Patel', img: ''},
    image: '/designs_horse.png',
    name: 'Horse',
    traits: 'Energetic, Passionate',
    bff: {name: 'Goat', img:''},
    nemesis: {name: 'Rat', img:''},
    years: '',
    element: '',
  },
  { 
    id: 'goat',
    archetype: 'The Wanderer',
    desc: 'Understated, innocent, lively Goats are faithful peacekeepers and delightful company. ',
    celeb1: {name: 'Emma Roberts', img: ''},
    celeb2: {name: 'Kyle Massey', img: ''},
    celeb3: {name: 'Travis Scott', img: ''},
    image: '/designs_goat.png',
    name: 'Goat',
    traits: 'Meek, Loyal',
    bff: {name: 'Horse', img:''},
    nemesis: {name: 'Ox', img:''},
    years: '',
    element: '',
  },
  { 
    id: 'monkey',
    archetype: 'The Investigator',
    desc: 'Monkeys are energetic, spontaneous, and fun-loving. Upbeat and whimsical Monkeys have a sixth sense for cool new hobbies and interests.',
    celeb1: {name: 'Cardi B', img: ''},
    celeb2: {name: 'Taylor Lautner', img: ''},
    celeb3: {name: 'Nina Agdal', img: ''},
    image: '/designs_monkey.png',
    name: 'Monkey',
    traits: 'Cautious, Clever, Energetic',
    bff: {name: 'Snake', img:''},
    nemesis: {name: 'Tiger', img:''},
    years: '',
    element: '',
  },
  { 
    id: 'rooster',
    archetype: 'The Arbiter',
    desc: 'Roosters are real-life Paladins who can be depended on to keep their promises, divide the check fairly, and never forget the sunscreen.',
    celeb1: {name: 'Ariana Grande', img: ''},
    celeb2: {name: 'Natalie Portman', img: ''},
    celeb3: {name: 'Roger Federer', img: ''},
    image: '/designs_rooster.png',
    name: 'Rooster',
    traits: 'Ambitious, Meticulous, Independent',
    bff: {name: 'Dragon', img:''},
    nemesis: {name: 'Rabbit', img:''},
    years: '',
    element: '',
  },
  { 
    id: 'dog',
    archetype: 'The Voyager',
    desc: 'Dogs are free-spirited and enthusiastic go-getters who are always itching for some friendly competition.',
    celeb1: {name: 'Justin Bieber', img: ''},
    celeb2: {name: 'Queen Latifah', img: ''},
    celeb3: {name: 'Jennifer Lopez', img: ''},
    image: '/designs_dog.png',
    name: 'Dog',
    traits: 'Loyal, Flexible, Gentle',
    bff: {name: 'Rabbit', img:''},
    nemesis: {name: 'Dragon', img:''},
    years: '',
    element: '',
  },
  { 
    id: 'pig',
    archetype: 'The Epicure',
    desc: 'Gentle, good-humored, refined, sensitive, and honest, Pigs are always quick with a smile or laugh and a kind word to brighten up your day.',
    celeb1: {name: 'Tupac', img: ''},
    celeb2: {name: 'Humphrey Bogart', img: ''},
    celeb3: {name: 'Dua Lipa', img: ''},
    image: '/designs_pig.png',
    name: 'Pig',
    traits: 'Optimistic, Gluttonous, Sleepy',
    bff: {name: 'Tiger', img:''},
    nemesis: {name: 'Snake', img:''},
    years: '',
    element: '',
  }    
]
