export const ProfileData = {
  'rat': {
    'rat' : "You and FIRSTNAME snap into place like two puzzle pieces—a perfect fit! But being perfect for each other doesn't make you objectively perfect, and honestly we all can't even stand ourselves sometimes. Love the good in FIRSTNAME, because that's the good in you, and accept the bad as the same—appreciating FIRSTNAME will guide you in loving yourself.",
    'ox': "Highly compatible from the start, you two complement each other perfectly! Together you'll lay down a solid, united foundation brick by brick, and your friendship will only grow closer and stronger as time goes by. As long as you can continue to treat each other with trust, honesty, and warmth, your bond is sure to withstand any trial.",
    'tiger': "Your dedication to the Golden Rule does your kindergarten teachers proud! You take pleasure in going out of your way to do nice things for FIRSTNAME, who'll be happy to return the favor and more besides. Your mutual dedication to your friendship will leave you both feeling secure in the knowledge that you've found something truly special.",
    'rabbit': "Though the two of you may not get along right from the get-go, once you do get going you'll go, and go, and go! While your disagreements may result in heated arguments, as long as you both remember in tense moments to take a step back to preserve each other's pride, you'll enjoy a dynamic and close friendship without a dull moment in sight.",
    'dragon': "You might not be the most demonstrative of friends, but why would you need to be? Your solid connection, built upon a deep and implicit understanding of each other, doesn't need words to make itself felt. All the same, it never hurts to let a buddy know how much they mean to you. You can even say 'don't be weird about it' after, if you must.",
    'snake': "Your friendship promises to be a bit of a rollercoaster ride, full of ups and downs and hurtling twists. While the drops may leave you feeling blindsided and dazed, the spectacular highs will bring you back together again. Practice patience and empathy during the low points, and you'll soon find that the track ahead is just one clear stretch home.",
    'horse': "You're a bit of an unconventional pairing, but somehow it just works! While your connection may suffer some fledgling growing pains, if you strive to embrace your differences and learn from each other, your friendship will glow up and probably get some kind of Instagram modeling deal. Jump in! A world of new and exciting possibilities awaits you!",
    'goat': "There might be some conflict between you two, but in a way that keeps things fresh and exciting rather than dangerously tense. It may take some time to get a steady fire going, but once you do, you'll enjoy the warmth of a friendship that will feel much like huddling around a campfire, roasting marshmallows and sharing secrets under a starry sky.",
    'monkey': "You two could be happy just sitting together doing nothing in particular, just enjoying being together and thinking there's no place you'd rather be. Your appreciation for each other is a quiet but constant warmth that will stay alive as long as you can trust each other with your vulnerabilities, fully sharing in the bad times as well as the good. ",
    'rooster': "Be sure to vocalize your feelings and preferences clearly, as FIRSTNAME is more than willing to follow your lead! If you take the initiative in keeping up a steady exchange of honest communication, your friendship can only grow stronger. Make sure to show your appreciation for FIRSTNAME in turn, and you two are bound to stand the test of time.",
    'dog': "When you two are just starting out, you may feel like you're constantly scrambling to find your footing and the right words to express yourself with. Instead of fretting over your insecurities, try letting FIRSTNAME take the reins! With time, this will bring you back to familiar ground, letting you feel right at home in your friendship.",
    'pig': "Your similarities gift you with a deep and instinctive understanding of each other, but this can prove draining; whenever you're rattled by the sight of your insecurities mirrored back at you, focus on each other's strengths and try to help each other grow. Learning from these moments will prove to be invaluable healing experiences for you both.",
  },
}
